import type { Metadata } from "next";
import "./globals.css";

import { Nunito, Titillium_Web } from 'next/font/google'

import { TooltipProvider } from "@/components/ui/tooltip"

import { ThemeProvider } from "./provider/theme-provider";

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
});
const titilum = Titillium_Web({
  weight: ["200", "300", "400", "600", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Derkysan | Desarrollo web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${nunito.className} ${titilum.className} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TooltipProvider>          
              {children}
            </TooltipProvider>
          </ThemeProvider>  
      </body>
    </html>
  );
}
